// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// V_lambda_tau
arma::mat V_lambda_tau(arma::mat K, arma::vec log_lambda_tau);
RcppExport SEXP _gwas_V_lambda_tau(SEXP KSEXP, SEXP log_lambda_tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type log_lambda_tau(log_lambda_tauSEXP);
    rcpp_result_gen = Rcpp::wrap(V_lambda_tau(K, log_lambda_tau));
    return rcpp_result_gen;
END_RCPP
}
// gamma_tilda
arma::vec gamma_tilda(arma::mat K, arma::mat X, arma::vec y, arma::vec log_lambda_tau);
RcppExport SEXP _gwas_gamma_tilda(SEXP KSEXP, SEXP XSEXP, SEXP ySEXP, SEXP log_lambda_tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type log_lambda_tau(log_lambda_tauSEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_tilda(K, X, y, log_lambda_tau));
    return rcpp_result_gen;
END_RCPP
}
// neglr_lambda_tau
double neglr_lambda_tau(arma::vec log_lambda_tau, arma::mat K, arma::mat X, arma::vec y);
RcppExport SEXP _gwas_neglr_lambda_tau(SEXP log_lambda_tauSEXP, SEXP KSEXP, SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type log_lambda_tau(log_lambda_tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(neglr_lambda_tau(log_lambda_tau, K, X, y));
    return rcpp_result_gen;
END_RCPP
}
// beta_hat_sigma_hat
arma::vec beta_hat_sigma_hat(arma:: mat K, arma::mat X, arma::vec y, arma::vec log_lambda_tau_hat);
RcppExport SEXP _gwas_beta_hat_sigma_hat(SEXP KSEXP, SEXP XSEXP, SEXP ySEXP, SEXP log_lambda_tau_hatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma:: mat >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type log_lambda_tau_hat(log_lambda_tau_hatSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_hat_sigma_hat(K, X, y, log_lambda_tau_hat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gwas_V_lambda_tau", (DL_FUNC) &_gwas_V_lambda_tau, 2},
    {"_gwas_gamma_tilda", (DL_FUNC) &_gwas_gamma_tilda, 4},
    {"_gwas_neglr_lambda_tau", (DL_FUNC) &_gwas_neglr_lambda_tau, 4},
    {"_gwas_beta_hat_sigma_hat", (DL_FUNC) &_gwas_beta_hat_sigma_hat, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_gwas(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
